### ISSUE TITLE
Primeira aula

### ISSUE THREAD

**Issue by jesse1983** [diegofns89/minhas-aulas#1]
No arquivo script.js:

1 - Faça 3 `alerts` diferentes
- "Bem vindo ao meu site"
-  "Essa é minha primeira aula de JS"
- "Daqui a pouco serei um excelente programador"

2 - Faça 3 `prompt`
- "Digite seu nome"
- "Digite a sua idade"
- "Digite a sua cidade"

3 - Agora, dê 3 `console.log`:
- 12 + 4
- "Diego Francisco"
- 144 / 12 + 10
- Comprimento da palavra "Paralelepipido"
- Comprimento da palavra "Ouviram do Ipiranga às margens plácidas"
- Comprimento da palavra "A"

4 - Ainda usando `console.log`:
- Uma sentença que retorne `true`  usando o comparador `>`
- Uma sentença que retorne `false` usando o comparador `>`

**Comment by diegofns89** [comment]
ok.
